---
title: "Group Project 2"
author: "A. Plekhov"
date: "`r Sys.Date()`"
output: html_document


---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(tidyverse)
library(reshape2)
library(scales)
library(cowplot)
library(kableExtra)
library(formattable)
library(knitr)

options(tinytex.verbose = TRUE)
```

```{r}
github_link <- "" 
df1 <- data.frame(read.csv(paste0(github_link, "time_series_covid19_confirmed_global.csv")))
df2 <- data.frame(read.csv(paste0(github_link, "time_series_covid19_deaths_global.csv")))
df3 <- data.frame(read.csv(paste0(github_link, "time_series_covid19_recovered_global.csv")))
df4 <- data.frame(read.csv(paste0(github_link, "time_series_covid19_confirmed_US.csv")))
df5 <- data.frame(read.csv(paste0(github_link, "time_series_covid19_deaths_US.csv")))


```



# 1. Global trajectory
```{r}

dataset1 <- list(df1,df2,df3)

dataset2 <- list()
for (df in dataset1){
   df0 <- df %>%  summarize(across(.cols = is.numeric,
                     .fns = list(SUM = sum),
                     .names = "{col}_{fn}")) %>%
                     select(5:ncol(df) -2)
  names(df0)<- gsub("[ˆA-Z_]", "",names(df0))
  names(df0) <- lubridate::mdy(names(df0))
  df00 <- reshape2::melt(df0)
  dataset2 <- append(dataset2,df00)
}
df_wide <- data.frame(dataset2) %>% 
  select( variable , 
          Confirmed = value , 
          Deaths = value.1 , 
          Recovered = value.2 )

df_long <- gather(df_wide,  value, cases,-variable)
df_long$variable <- as.Date(df_long$variable)

ggplot(df_long)  + geom_point(aes(x=variable, y=cases, color= value))+
    labs(title="Global trajectory of COVID-19",
         x= "Date",
         y = " Cases")+
    scale_y_continuous(labels = comma)+
    scale_x_date(date_breaks = "6 month")+
    labs(color = "Global Data Set")+ 
    scale_x_date(date_labels = "%b")

```



# 2. Global Map
```{r}
library(leaflet)
library(htmltools)
library(tidyverse)

df31 <- df1 %>% rename(Confirmed = ncol(df1) )%>% select(Country.Region,Lat,Long, ncol(df1)) 

df32 <- df2 %>% rename(Deaths = ncol(df2) )%>% select(Lat,Long, ncol(df2))
df33 <- df3 %>% rename(Recovered = ncol(df3) ) %>% select(Lat,Long, ncol(df3))
df34 <- merge(df31, df32, by = c("Lat", "Long"),all = TRUE)
df35 <- merge(df33, df34, by = c("Lat", "Long"),all = TRUE)
 
df36 <- df35[!is.na(df35$Long), ]

leaflet(df36) %>% addTiles()  %>% addCircles(lat= ~Lat, lng= ~Long , group = "Confirmed",
                                                  radius = df36$Confirmed/15,
                                                  color = "blue",
                                                  label = ~htmlEscape(df36$"Country.Region")
                                                  )%>%
                                  addCircles(lat= ~Lat, lng= ~Long , group = "Deaths",
                                                  radius = df36$Deaths/30,
                                                  color = "red"
                                                  )%>%
                                  addCircles(lat= ~Lat, lng= ~Long , group = "Recovered",
                                                  radius = df36$Recovered/20,
                                                  color = "green"
                                                  )%>%
                                  
  addLayersControl(overlayGroups = c("Confirmed","Deaths","Recovered"),
    options = layersControlOptions(collapsed = FALSE))

```


# 3. Narrowing Down Hot Spots
```{r}


df21 <- df1 %>% select(Country.Region, ncol(df1)) %>%
    group_by(Country.Region) %>% 
    summarize(across(.cols = is.numeric,
                     .fns = list(SUM = sum),
                     .names = "Count")) %>%
    arrange(desc(Count)) %>%
  rename(Country = Country.Region  )

df22 <- df2 %>% select(Country.Region, ncol(df2)) %>%
    group_by(Country.Region) %>% 
    summarize(across(.cols = is.numeric,
                     .fns = list(SUM = sum),
                     .names = "Count")) %>%
    arrange(desc(Count)) %>%
  rename(Country = Country.Region  )

df23 <- df3 %>% select(Country.Region, ncol(df3)) %>%
    group_by(Country.Region) %>% 
    summarize(across(.cols = is.numeric,
                     .fns = list(SUM = sum),
                     .names = "Count")) %>%
    arrange(desc(Count)) %>%
  rename(Country = Country.Region  )

df24 <- cbind("Rank"=1:nrow(df21),df21,df22,df23)


kbl(df24) %>%
   add_header_above(c( "Confirmations" = 3, "Deaths" = 2, "Recoveries" = 2))%>%
   kable_minimal()%>%
   kableExtra::scroll_box(width = "100%", height = "500px")
   


```


# 4. Zooming Into Our State
```{r}
dataset41 <- list(df4,df5)

dataset42 <- list()

for (df in dataset41){

df41 <- df %>% group_by(Province_State) %>% 
    summarize(across(.cols = is.numeric,
                     .fns = list(SUM = sum),
                     .names = "{col}_{fn}")) 
names(df41)<- gsub("[ˆA-Z_]", "",names(df41))
names(df41) <- lubridate::mdy(names(df41))
df42 <- subset(df41[6,7:ncol(df41)])
df43 <- reshape2::melt(df42)
dataset42 <- append(dataset42,df43)
}
dataset42[[4]] <- dataset42[[4]][-1]
df43 <- data.frame(dataset42[-3])   %>%
     select( variable , 
          Confirmed = value , 
          Deaths = value.1)
df_long4 <- gather(df43,  value, cases,-variable)
df_long4$variable <- as.Date(df_long4$variable)



ggplot(df_long4)  + geom_point(aes(x=variable, y=cases, color= value))+
    labs(title="California trajectory of COVID-19",
         x= "Date",
         y = " Cases")+
    scale_y_continuous(labels = comma)+
    scale_x_date(date_breaks = "6 month")+
    labs(color = "California Total")+ 
    scale_x_date(date_labels = "%b") +
    geom_vline( aes(xintercept = unclass(as.Date("2020-03-18"))),   linetype="dashed", color = "red")


df_c <- filter(df4, Province_State == "California") %>% top_n( n =3) %>% select(6,12:ncol(df4))

names(df_c)<- gsub("[ˆA-Z_]", "",names(df_c))
names(df_c) <- lubridate::mdy(names(df_c))
df52 <- subset(df_c[6,7:ncol(df_c)])
df53 <- reshape2::melt(df_c) 
names(df53)[1] <- "City"

df53$variable <- as.Date(df53$variable)

ggplot(df53)  + geom_point(aes(x=variable, y=value, color= City))+
    labs(
         x= "Date",
         y = " Cases")+
    scale_y_continuous(labels = comma)+
    scale_x_date(date_breaks = "6 month")+
    labs(color = "Top Confirmed Cities")+ 
    scale_x_date(date_labels = "%b") +
    geom_vline( aes(xintercept = unclass(as.Date("2020-03-18"))),   linetype="dashed", color = "red")

```

# 5. Digging Deeper 
```{r}

names(df4)[length(names(df4))]<-"Confirmed" 
df_c <- df4 %>%  select(11 ,ncol(df4) ) 

names(df5)[length(names(df5))]<-"Deaths" 
df_d <- df5  %>% select(11,12,ncol(df5))

df_a <- merge(x = df_c, y = df_d, by = "Combined_Key")

p1 <- ggplot(df_a) + geom_point(aes(x=log10(Population) , y=log10(Confirmed)), color = "blue")+
  
   labs(title="Conformations vs. Population",
         x= "Population",
         y = "Conformation Counts")+
  
   
   scale_x_continuous(
     limits = c(3, 7),
     label = 64*16^(0:4)
  )+
   scale_y_continuous(
     limits = c(2, 6),
     label = 64*16^(0:4)
  )
    #scale_x_continuous(breaks = 64*16^(0:5), labels = trans_format("log10", math_format(64*16^.x)))+
   # scale_y_continuous(breaks = 8*16^(0:4), labels = trans_format("log10", math_format(8*16^(0:4)^.x)))

p2 <- ggplot(df_a) + geom_point(aes(x=log10(Population) , y=log10(Deaths)), color = "red")+
   labs(title="Deaths vs. Conformations",
         x= "Confirmation Counts",
         y = "Death Counts")+
   scale_x_continuous(
     limits = c(4, 7),
     label = 256*16^(0:3)
  )+
   scale_y_continuous(
     limits = c(2, 5),
     label = 32*16^(0:3)
)
  

plot_grid(p1, p2) 


```

# 6. GitHub Log
## Link to the GitHub repository
>[https://github.com/aplekhov777/Group_Project_2](https://github.com/aplekhov777/Group_Project_2)

```{bash}
git log --pretty=format:"%nSubject: %s%nAuthor: %aN%nDate: %aD%nBody: %b"
```
  
